version: '3.1'

services:

  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  kafkaserver:
    image: spotify/kafka
    container_name: kafka
    hostname: kafkaserver
    ports:
    - 2181:2181
    - 9092:9092
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      CONSUMER_THREADS: 1
      TOPICS: click
      GROUP_ID: clickstream

  kafka_manager:
    image: mzagar/kafka-manager-docker:1.3.3.4
    container_name: kafkamanager
    ports:
    - 9999:9000
    environment:
      ZK_HOSTS: "kafkaserver:2181"